name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger only on main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and push Docker image
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: yourdockerhubuser/icd-predictor:latest

    # Step 5: (Optional) Deploy to Kubernetes
    # If you have Kubernetes set up
    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl set image deployment/icd-app icd-container=yourdockerhubuser/icd-predictor:latest
